name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm repositories
        run: |
          helm repo add stable https://charts.helm.sh/stable

      - name: Lint chart
        run: |
          helm lint charts/trivy-ui/

      - name: Package chart
        run: |
          helm package charts/trivy-ui/
          ls -la *.tgz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub Helm Registry
        run: |
          # Push chart to Docker Hub Helm registry
          helm push trivy-ui-*.tgz oci://registry-1.docker.io/locustbaby
          echo "Chart pushed to Docker Hub: oci://registry-1.docker.io/locustbaby/trivy-ui"



      - name: Output chart URLs
        run: |
          echo "Chart published to Docker Hub: oci://registry-1.docker.io/locustbaby/trivy-ui"
          echo "Chart package: $(ls *.tgz)"
          echo ""
          echo "Users can install with:"
          echo "helm install my-trivy-ui oci://registry-1.docker.io/locustbaby/trivy-ui"
